// <auto-generated />
using System;
using HrAppSimple.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrAppSimple.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HrAppSimple.Models.Angajat", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricula"));

                    b.Property<int>("CodDepartament")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentCodDepartament")
                        .HasColumnType("int");

                    b.HasKey("Matricula");

                    b.HasIndex("DepartamentCodDepartament");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("HrAppSimple.Models.AngajatProiect", b =>
                {
                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<int>("CodProiect")
                        .HasColumnType("int");

                    b.HasKey("Matricula", "CodProiect");

                    b.HasIndex("CodProiect");

                    b.ToTable("AngajatProiect");
                });

            modelBuilder.Entity("HrAppSimple.Models.Departament", b =>
                {
                    b.Property<int>("CodDepartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDepartament"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodDepartament");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("HrAppSimple.Models.DetaliiAngajat", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricula"));

                    b.Property<DateTime>("DataAngajare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNastere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatriculaAng")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.HasIndex("MatriculaAng")
                        .IsUnique();

                    b.ToTable("DetaliiAngajat");
                });

            modelBuilder.Entity("HrAppSimple.Models.Locatie", b =>
                {
                    b.Property<int>("CodLocatie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLocatie"));

                    b.Property<int>("CodDepartament")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentCodDepartament")
                        .HasColumnType("int");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodLocatie");

                    b.HasIndex("DepartamentCodDepartament");

                    b.ToTable("Locatie");
                });

            modelBuilder.Entity("HrAppSimple.Models.Proiect", b =>
                {
                    b.Property<int>("CodProiect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodProiect"));

                    b.Property<DateTime>("DataPredare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodProiect");

                    b.ToTable("Proiect");
                });

            modelBuilder.Entity("HrAppSimple.Models.Angajat", b =>
                {
                    b.HasOne("HrAppSimple.Models.Departament", "Departament")
                        .WithMany("Angajat")
                        .HasForeignKey("DepartamentCodDepartament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("HrAppSimple.Models.AngajatProiect", b =>
                {
                    b.HasOne("HrAppSimple.Models.Proiect", "Proiect")
                        .WithMany("AngajatProiect")
                        .HasForeignKey("CodProiect")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrAppSimple.Models.Angajat", "Angajat")
                        .WithMany("AngajatProiect")
                        .HasForeignKey("Matricula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");

                    b.Navigation("Proiect");
                });

            modelBuilder.Entity("HrAppSimple.Models.DetaliiAngajat", b =>
                {
                    b.HasOne("HrAppSimple.Models.Angajat", "Angajat")
                        .WithOne("DetaliiAngajat")
                        .HasForeignKey("HrAppSimple.Models.DetaliiAngajat", "MatriculaAng")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");
                });

            modelBuilder.Entity("HrAppSimple.Models.Locatie", b =>
                {
                    b.HasOne("HrAppSimple.Models.Departament", "Departament")
                        .WithMany("Locatie")
                        .HasForeignKey("DepartamentCodDepartament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("HrAppSimple.Models.Angajat", b =>
                {
                    b.Navigation("AngajatProiect");

                    b.Navigation("DetaliiAngajat")
                        .IsRequired();
                });

            modelBuilder.Entity("HrAppSimple.Models.Departament", b =>
                {
                    b.Navigation("Angajat");

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("HrAppSimple.Models.Proiect", b =>
                {
                    b.Navigation("AngajatProiect");
                });
#pragma warning restore 612, 618
        }
    }
}
